'use client';

import { ArrowLeft, CheckCircle2, Clock3, Mail, Phone } from 'lucide-react';
import { FormEvent, useState } from 'react';

export default function ContactPage() {
  const [sent, setSent] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); }
  return <main className="legal-page"><header className="legal-header"><div className="container"><a className="brand" href="/"><span className="brand-mark">M</span><span>MONOGEN</span></a></div></header><div className="contact-page"><a className="back-link" href="/"><ArrowLeft size={17} /> トップページへ戻る</a><div className="contact-page-title"><p className="eyebrow">Contact</p><h1>お問い合わせ</h1><p>ご希望のサービスやご相談内容をお聞かせください。内容を確認のうえ、担当者よりご連絡します。</p></div><div className="contact-layout"><aside id="phone" className="contact-sidebar"><h2>お電話でのご相談</h2><p>お急ぎのご相談は、お電話で承ります。</p><div className="phone-pending"><Phone size={21} /><strong>電話番号は掲載準備中です</strong><span>正式な代表番号の確認後に掲載します。</span></div><div className="contact-info"><Mail size={18} /><div><b>メールでのお問い合わせ</b><a href="mailto:info@monogen.co.jp">info@monogen.co.jp</a></div></div><div className="contact-info"><Clock3 size={18} /><div><b>受付時間</b><span>平日 9:00 — 18:00</span></div></div></aside><section className="contact-form-wrap">{sent ? <div className="form-complete"><CheckCircle2 size={42} /><h2>お問い合わせを受け付けました</h2><p>内容を確認のうえ、担当者よりご連絡します。</p><button onClick={() => setSent(false)}>続けてお問い合わせする</button></div> : <form onSubmit={submit}><label>お問い合わせ種別<select required defaultValue=""><option value="" disabled>選択してください</option><option>レンタカーについて</option><option>カーリースについて</option><option>自動車保険について</option><option>法人のお客様向けサービスについて</option><option>その他</option></select></label><label>お名前<input required name="name" autoComplete="name" /></label><label>メールアドレス<input required type="email" name="email" autoComplete="email" /></label><label>電話番号<input type="tel" name="tel" autoComplete="tel" /></label><label>お問い合わせ内容<textarea required name="message" rows={6} /></label><p className="form-note">送信前に<a href="/privacy">プライバシーポリシー</a>をご確認ください。</p><button type="submit" className="form-submit">入力内容を送信する</button></form>}</section></div></div></main>;
}
