import { ArrowRight, CarFront, ChevronRight, CircleCheck, Menu, Phone, ShieldCheck, Sparkles } from 'lucide-react';

const services = [
  { number: '01', icon: CarFront, title: 'レンタカー', text: '必要なときに、必要な一台を。法人利用から週末のお出かけまで、軽やかな移動を支えます。', link: '車種・料金を見る', image: '/rental-service.png' },
  { number: '02', icon: Sparkles, title: 'カーリース', text: '初期費用を抑え、月々定額で。クルマのある毎日を、もっとシンプルにする新しい選択です。', link: 'リースのご相談', image: '/lease-service.png' },
  { number: '03', icon: ShieldCheck, title: '自動車保険', text: 'もしものときにも、いつもの安心を。暮らし方に寄り添う補償を一緒に考えます。', link: '保険について知る', image: '/insurance-service.png' },
];

export default function Home() {
  return <main>
    <section className="hero" id="top"><nav className="nav container"><a className="brand" href="#top"><span className="brand-mark">M</span><span>MONOGEN</span></a><div className="nav-links"><a href="#service">サービス</a><a href="#about">私たちについて</a><a href="#news">お知らせ</a></div><a className="nav-contact" href="/contact">お問い合わせ <ArrowRight size={16} /></a><button className="menu" aria-label="メニューを開く"><Menu size={23} /></button></nav><div className="hero-shade" /><div className="container hero-content"><p className="eyebrow light">Mobility, made personal.</p><h1>移動を、<br />あなたらしく。</h1><p className="hero-copy">レンタカー、カーリース、自動車保険。<br />毎日の移動に、心地よい選択肢を。</p><a className="hero-cta" href="#service">サービスを知る <span><ArrowRight size={19} /></span></a></div><div className="hero-caption">SCROLL TO EXPLORE <span /></div></section>
    <section className="intro container" id="about"><p className="eyebrow">About MONOGEN</p><div className="intro-grid"><h2>クルマのそばに、<br />いつも確かな安心を。</h2><div><p>MONOGENは、地域に根ざしたモビリティのパートナーです。必要な一台との出会いから、長く続く安心まで。ひとりひとりの暮らしに合う、誠実で気持ちのよいサービスをお届けします。</p><a className="text-link" href="#contact">MONOGENについて <ArrowRight size={17} /></a></div></div></section>
    <section className="services" id="service"><div className="container"><div className="section-heading"><div><p className="eyebrow">Our services</p><h2>あなたの移動に、<br />3つの答えを。</h2></div><p>クルマに関することなら、<br />まずはMONOGENへ。</p></div><div className="service-list">{services.map(({ number, icon: Icon, title, text, link, image }) => <article className={`service-card ${image ? 'with-image' : ''}`} key={title}>{image && <img src={image} alt="" />}<div className="service-top"><span>{number}</span><Icon strokeWidth={1.5} size={31} /></div><h3>{title}</h3><p>{text}</p><a href="#contact">{link}<ChevronRight size={18} /></a></article>)}</div></div></section>
    <section className="corporate"><div className="container corporate-grid"><div className="corporate-copy"><p className="eyebrow">For business</p><h2>法人の移動を、<br />もっと効率よく、しなやかに。</h2><p>営業車・社用車のリースから、短期のレンタル、保険まで。車両管理にかかる手間とコストを見直し、事業に集中できる環境をつくります。</p><ul><li>用途・台数に合わせた車両提案</li><li>保守・保険までまとめてサポート</li><li>急な増車にも柔軟に対応</li></ul><a className="text-link" href="#contact">法人のお客様へ <ArrowRight size={17} /></a></div><img src="/corporate-fleet.png" alt="法人向けに管理された車両" /></div></section>
    <section className="promise container"><div className="promise-image"><img src="/promise-mobility.png" alt="夜の自宅前に停められた車" /></div><div><p className="eyebrow">Our promise</p><h2>選ぶ時間も、<br />乗る時間も、もっと豊かに。</h2><p className="promise-copy">分かりやすいご案内、丁寧な整備、そして気軽に頼れる距離感。私たちは、移動の前も後も心地よくあることを大切にしています。</p><div className="checks"><span><CircleCheck size={18} /> 明瞭な料金体系</span><span><CircleCheck size={18} /> 万全のサポート</span><span><CircleCheck size={18} /> 地域密着の安心</span></div></div></section>
    <section className="news" id="news"><div className="container news-wrap"><div><p className="eyebrow">News</p><h2>お知らせ</h2></div><div className="news-list"><a href="#news"><time>2026.09.01</time><span>MONOGENのウェブサイトをリニューアルしました</span><ArrowRight size={17} /></a><a href="#news"><time>2026.08.20</time><span>カーリースのご相談を承っています</span><ArrowRight size={17} /></a><a href="#news"><time>2026.08.01</time><span>秋のレンタカーご予約受付を開始しました</span><ArrowRight size={17} /></a></div></div></section>
    <section className="contact" id="contact"><div className="container contact-inner"><p className="eyebrow light">Contact</p><h2>クルマのこと、<br />気軽にご相談ください。</h2><p className="contact-intro">レンタカー・リース・保険・法人車両のご相談まで、専任スタッフが承ります。</p><div className="contact-actions"><a href="/contact#phone"><Phone size={19} /> お電話でのお問い合わせ</a><a href="/contact">お問い合わせフォーム <ArrowRight size={19} /></a></div></div></section><footer><div className="container footer-inner"><a className="brand" href="#top"><span className="brand-mark">M</span><span>MONOGEN</span></a><p>© MONOGEN Co., Ltd.</p><div><a href="/privacy">プライバシーポリシー</a><a href="/company">会社概要</a></div></div></footer>
  </main>;
}
